Repository projectcalico/cni-plugin, pull requests merged in 2018-05, with the labels that each got.

#526 BUG FIX: Make install-cni.sh check if the etcd cert file exist.
  k8s-install/scripts/install-cni.sh
Labels: cherry-pick-candidate, release-note-required

#530 Cherry-pick 526 and 527 into v3.1 release branch
  k8s-install/scripts/install-cni.sh
Labels: release-note-required

#531 Cherry-picking PRs 526, 527, 481, and 483 into v3.0
  k8s-install/scripts/install-cni.sh
Labels: release-note-required

#529 Always allocate a new IP on k8sCmdAdd
  calico_cni_k8s_test.go
  k8s/k8s.go
Labels: cherry-pick-candidate, release-note-required

#535 Add GCR images to standard tag/push targets
  Makefile
Labels: cherry-pick-candidate

#537 [release-v3.0] cherry-pick: Always allocate a new IP on k8sCmdAdd
  calico_cni_k8s_test.go
  k8s/k8s.go
Labels: release-note-required

#538 [release-v3.1] cherry-pick: Always allocate a new IP on k8sCmdAdd
  calico_cni_k8s_test.go
  k8s/k8s.go
Labels: release-note-required
