Repository projectcalico/cni-plugin, pull requests merged in 2018-04, with the labels that each got.

#502 [v3.0] Backport s390x build support
  .dockerignore
  Dockerfile-s390x
  Makefile
Labels: release-note-required

#501 Allow sysctl configuration
  calico.go
  calico_cni_test.go
  types/types.go
  utils/network.go
Labels: cherry-pick-candidate, release-note-required

#508 [v3.0] cherry pick 501
  calico.go
  calico_cni_test.go
  types/types.go
  utils/network.go
Labels: release-note-required

#509 [v3.1] cherry pick 501
  calico.go
  calico_cni_test.go
  types/types.go
  utils/network.go
Labels: release-note-required

#505 Disable ipAddrsNoIpam by default
  calico.go
  calico_cni_k8s_test.go
  calico_cni_test.go
  k8s/k8s.go
  types/types.go
Labels: release-note-required

#511 Update release targets
  Makefile
  RELEASING.md
  k8s-install/scripts/install_cni_test.go
Labels: cherry-pick-candidate
