Repository projectcalico/cni-plugin, pull requests merged in 2019-04, with the labels that each got.

#724 [master] Automatic patch of libcalico-go to 43c1da882b70aba9d0325e7de4393439ef202550
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#725 Upgrade base image up to debian:buster-slim
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: docs-not-required, release-note-not-required

#729 [master] Automatic update of libcalico-go to 43d572414857cc6f4d7242d9a23422cbc552f84a
  glide.lock
  glide.yaml
Labels: docs-not-reqiured, release-note-not-required

#730 Retry on IPv6 listing
  internal/pkg/utils/network_linux.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#728 Adding -C option to curl to ensure download of cni-plugins wont fail
  Makefile
Labels: docs-not-required, release-note-not-required

#732 Automated cherry pick of #730: Retry on IPv6 listing
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-required

#733 Automated cherry pick of #730: Retry on IPv6 listing
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-required

#731 Automated cherry pick of #730: Retry on IPv6 listing
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-required

#735 [release-v3.6] Automatic patch of libcalico-go to 24a5a971c54bf0f43417bbfccd0b31e7ffa19a98
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#736 [release-v3.5] Automatic patch of libcalico-go to aae6c757ef3745eb6ecb45351470e66c54fd9e13
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#737 [release-v3.7] Automatic patch of libcalico-go to 6860ff2cfd923a870ff7a76563ce825d6e47adb8
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required
