Repository projectcalico/cni-plugin, pull requests merged in 2019-11, with the labels that each got.

#802 [release-v3.10] Automatic patch of libcalico-go to 8f81e1e344ce1dc436b066ea242e4da5df765a97
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#803 [release-v3.9] Automatic patch of libcalico-go to 1891db7ae73bcafe01c90943f5eaac25ec53c96d
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#801 Change base image from debian slim => ubi
  .dockerignore
  Dockerfile.amd64
  Makefile
Labels: docs-not-required, release-note-required

#806 Move package_name to the top so -w option works in Makefile
  Makefile
Labels: docs-pr-required, release-note-required

#807 Add timeouts to cmdAdd() and cmdDel()
  pkg/ipamplugin/ipam_plugin.go
Labels: docs-not-required, release-note-not-required

#808 remove the whole bin/ directory
  Makefile
Labels: docs-not-required, release-note-not-required

#809 Move common Makefile targets to Makefile.common
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#810 Switch Makefile.common from wget to curl, remove wget dependency
  Makefile
Labels: docs-not-required, release-note-not-required

#811 Test dual stack IP allocation and pod annotation
  go.mod
  go.sum
  internal/pkg/testutils/utils_linux.go
  tests/calico_cni_k8s_test.go
Labels: docs-pr-required, release-note-not-required

#812 Move image build/push targets back to local Makefile
  Makefile
Labels: docs-not-required, release-note-not-required
