Repository projectcalico/cni-plugin, pull requests merged in 2019-12, with the labels that each got.

#813 move all k8s.io packages to kubernetes v1.16.3
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#817 Increase context timeout to 90s
  pkg/ipamplugin/ipam_plugin.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#814 release-v3.10 - Cherry-pick timeouts addition
  pkg/ipamplugin/ipam_plugin.go
Labels: docs-not-required, release-note-required

#815 release-v3.9 - Cherry-pick timeouts addition
  pkg/ipamplugin/ipam_plugin.go
Labels: docs-not-required, release-note-required

#816 release-v3.8 - Cherry-pick timeouts addition
  pkg/ipamplugin/ipam_plugin.go
Labels: docs-not-required, release-note-required

#819 Connect to datastore before installing CNI config
  k8s-install/scripts/install-cni.sh
  k8s-install/scripts/install_cni_test.go
  pkg/plugin/plugin.go
Labels: docs-not-required, release-note-required

#823 Add 'Makefile.common*' to .gitignore
  .gitignore
Labels: docs-not-required, release-note-not-required

#826 Update go-build
  Makefile
Labels: docs-not-required, release-note-not-required
