Repository projectcalico/cni-plugin, pull requests merged in 2019-06, with the labels that each got.

#750 Fix upgrade-ipam lockin wrong directory
  pkg/upgrade/migrate.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#753 Add etcd SRV discovery support
  internal/pkg/utils/utils.go
  k8s-install/scripts/calico.conf.default
  k8s-install/scripts/expected_10-calico.conf
  k8s-install/scripts/expected_10-calico.conf.alternate
  k8s-install/scripts/install-cni.sh
  k8s-install/scripts/test-templates/calico.conf.alternate
  pkg/types/types.go
Labels: docs-not-required, release-note-not-required

#754 Handle migrating an IP that is already migrated
  pkg/upgrade/migrate.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#755 Automated cherry pick of #750: Fix upgrade-ipam lockin wrong directory
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#757 [release-v3.7] Automatic patch of libcalico-go to 8898b03e9d624b38f903a530ffc40f8a39a433d9
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#756 Automated cherry pick of #750: Fix upgrade-ipam lockin wrong directory
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#760 Added retry on node update in upgrade-ipam after assigning ipip-tunne…
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required
