Repository projectcalico/cni-plugin, pull requests merged in 2019-05, with the labels that each got.

#739 Switching image base to debian:9.8-slim
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#740 Switching image base to debian:9.8-slim
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: docs-not-required, release-note-required

#726 Handle nil pointers better in migration script
  pkg/upgrade/migrate.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#741 Automated cherry pick of #726: Handle nil pointers better in migration script
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#742 Automated cherry pick of #726: Handle nil pointers better in migration script
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#743 Always rebuild when DEV_BUILD=true
  Makefile
Labels: docs-not-required, release-note-not-required

#744 Increase K8s version to 1.14.1
  Makefile
Labels: docs-not-required, release-note-not-required

#745 Add bandwidth plugin and update cni plugins to v0.8.0
  Makefile
Labels: docs-pr-required, release-note-required

#746 Changed order of releasing IP and removing interface
  pkg/k8s/k8s.go
Labels: docs-not-required, release-note-required
