Repository projectcalico/cni-plugin, pull requests merged in 2020-09, with the labels that each got.

#943 Merge pull request #942 from neiljerram/fix-node-name-var
  pkg/install/install.go
  pkg/install/install_test.go
Labels: docs-not-required, release-note-not-required

#945 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#946 [release-v3.16] Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#940 Revert broken artifact naming
  Makefile
Labels: docs-not-required, release-note-not-required

#948 Fix installation of etcd secrets into config file
  pkg/install/install.go
  pkg/install/install_test.go
Labels: docs-not-required, release-note-required

#949 Automated cherry pick of #948: Fix installation of etcd secrets into config file
  pkg/install/install.go
  pkg/install/install_test.go
Labels: docs-not-required, release-note-required

#953 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#952 Add pin update pipeline
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
  Makefile
Labels: docs-pr-required, release-note-required

#954 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#956 Allow semaphore-run-auto-pin-update-workflows to set the SEMAPHORE_PROJECT_ID (only default it if it's not set)
  Makefile
Labels: docs-not-required, release-note-not-required
