Repository projectcalico/cni-plugin, pull requests merged in 2020-06, with the labels that each got.

#888 Update libcalico-go for new CRDs
  .gitignore
  Makefile
  go.mod
  go.sum
  tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-not-required

#890 Clean go.sum
  go.sum
Labels: docs-not-required, release-note-not-required

#889 k8s-install: install-cni.sh now aborts when calico -v doesn't succeed
  k8s-install/scripts/install-cni.sh
Labels: docs-not-required, release-note-required

#892 Fix go.sum
  go.sum
Labels: docs-not-required, release-note-not-required

#886 namespaces support for mesos
  pkg/plugin/plugin.go
Labels: docs-pr-required, release-note-required

#897 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#899 Run current version of goimports.
  internal/pkg/azure/azure_suite_test.go
  internal/pkg/testutils/utils.go
  internal/pkg/testutils/utils_linux.go
  internal/pkg/utils/utils.go
  internal/pkg/utils/utils_test.go
  pkg/dataplane/dataplane.go
  pkg/dataplane/grpc/grpc_dataplane.go
  pkg/dataplane/grpc/proto/cnibackend.pb.go
  pkg/dataplane/grpc/test_server.go
  pkg/dataplane/linux/linux_dataplane.go
  pkg/ipamplugin/ipam_plugin.go
  pkg/k8s/k8s.go
  pkg/plugin/plugin.go
  tests/calico_cni_ipam_test.go
  tests/calico_cni_k8s_test.go
  tests/calico_cni_test.go
Labels: docs-pr-required, release-note-required

#902 Fix vulnerabilities
  Dockerfile.amd64
Labels: docs-pr-required, release-note-required
