Repository projectcalico/cni-plugin, pull requests merged in 2020-11, with the labels that each got.

#964 [master] Automatic update of sempahore YAMLs.
  .semaphore/cleanup.yml
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#965 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#966 Fix issue moving files into place during install
  pkg/install/install.go
  pkg/install/install_test.go
Labels: docs-not-required, release-note-required

#969 Automated cherry pick of #966: Fix issue moving files into place during install
  pkg/install/install.go
  pkg/install/install_test.go
Labels: docs-not-required, release-note-required

#967 Fix error message in IP assignment which references the field it failed to set
  pkg/upgrade/migrate.go
Labels: docs-pr-required, release-note-required

#970 Fix error message in IP assignment which references the field it fail…
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#971 Fix release branch pin update regex (add ^ to start)
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#972 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#973 Finish Semaphore V2 migration
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#974 Use quay credentials to push images
  .semaphore/semaphore.yml
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#975 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#968 Fix a bug that prevented failed attempts at unlocking the datastore d…
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#978 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#979 Fix update CNI binary logic
  pkg/install/install.go
Labels: docs-not-required, release-note-required

#980 Fix update CNI binary logic
  pkg/install/install.go
Labels: docs-pr-required, release-note-required

#981 Fix update CNI binary logic
  pkg/install/install.go
Labels: docs-not-required, release-note-required

#982 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#983 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#984 update pins
  go.mod
  go.sum
  internal/pkg/testutils/utils.go
  internal/pkg/testutils/utils_windows.go
  pkg/k8s/k8s.go
  pkg/upgrade/migrate.go
  tests/calico_cni_k8s_test.go
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-not-required, release-note-not-required

#985 Add a file lock to serialise IPAM allocations.
  go.mod
  go.sum
  pkg/ipamplugin/ipam_lock_linux.go
  pkg/ipamplugin/ipam_lock_windows.go
  pkg/ipamplugin/ipam_plugin.go
  pkg/types/types.go
Labels: docs-not-required, release-note-required
