Repository projectcalico/cni-plugin, pull requests merged in 2020-05, with the labels that each got.

#870 Add licenses to built image
  .dockerignore
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
  README.md
  licenses/Apache-2.0
  licenses/BSD
  licenses/GPLv2
  licenses/ISC
  licenses/MIT
  licenses/Mozilla-public
Labels: docs-not-required, release-note-not-required

#871 Automated cherry pick of #870: Add licenses to built image
  .dockerignore
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
  README.md
  licenses/Apache-2.0
  licenses/BSD
  licenses/GPLv2
  licenses/ISC
  licenses/MIT
  licenses/Mozilla-public
Labels: docs-not-required, release-note-not-required

#873 [release-v3.14] Automatic update of libcalico-go to dda4a7964ffad2dace251d0a8f95c2ba78ec91f8
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#878 Disable accept_ra for the host veth
  pkg/dataplane/linux/linux_dataplane.go
Labels: docs-not-required, release-note-not-required

#876 Fix ppc64le Dockerfile
  Dockerfile.ppc64le
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#880 Automated cherry pick of #879: Disable accept_ra for the host veth
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-not-required

#885 Automated cherry pick of #884: Disable accept_ra for the host veth
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-not-required

#884 Automated cherry pick of #883: Disable accept_ra for the host veth
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-not-required

#883 Automated cherry pick of #882: Disable accept_ra for the host veth
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-not-required

#882 Automated cherry pick of #881: Disable accept_ra for the host veth
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-not-required

#881 Automated cherry pick of #880: Disable accept_ra for the host veth
  internal/pkg/utils/network_linux.go
Labels: docs-not-required, release-note-not-required

#879 Automated cherry pick of #878: Disable accept_ra for the host veth
  pkg/dataplane/linux/linux_dataplane.go
Labels: docs-not-required, release-note-not-required

#887 Update CNI plugins version
  Makefile
Labels: docs-not-required, release-note-required
