Repository projectcalico/cni-plugin, pull requests merged in 2020-01, with the labels that each got.

#824 Fix containerID read during IPAM migration
  pkg/upgrade/migrate.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#828 release-v3.10 - Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#827 release-v3.9 - Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#825 release-v3.8 - Update libcalico-go
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#829 release-v3.11 - Cherry-pick Fix containerID read during IPAM migration
  pkg/upgrade/migrate.go
Labels: cherry-pick-completed, docs-not-required, release-note-required

#832 release-v3.8 - Cherry-pick Fix containerID read during IPAM migration
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#831 release-v3.9 - Cherry-pick Fix containerID read during IPAM migration
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#830 release-v3.10 - Cherry-pick Fix containerID read during IPAM migration
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-required

#833 Fix release image push
  Makefile
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#834 Cherry-picck Merge pull request #833 from lmm/lmm-fix-image-push
  Makefile
Labels: docs-pr-required, release-note-required
