Repository projectcalico/cni-plugin, pull requests merged in 2020-12, with the labels that each got.

#991 Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#992 Automated cherry pick of #991: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-pr-required, release-note-required

#993 Automated cherry pick of #991: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#994 Update semv2 to run full CI
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#995 Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-pr-required, release-note-required

#997 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#998 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#996 Automated cherry pick of #995: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-pr-required, release-note-required

#999 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1000 Make sure we log out a final error from CNI ADD/DEL.
  pkg/plugin/plugin.go
Labels: docs-not-required, release-note-required

#1001 Log at info by default.
  internal/pkg/utils/utils.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1005 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
