Repository projectcalico/cni-plugin, pull requests merged in 2020-08, with the labels that each got.

#924 Added Windows support
  .semaphore/cleanup.yml
  .semaphore/run-win-fv.sh
  .semaphore/semaphore.yml
  Makefile
  cmd/calico/calico.go
  go.mod
  go.sum
  internal/pkg/testutils/utils.go
  internal/pkg/testutils/utils_linux.go
  internal/pkg/testutils/utils_windows.go
  internal/pkg/utils/network_linux.go
  internal/pkg/utils/network_windows.go
  internal/pkg/utils/utils.go
  internal/pkg/utils/winpol/windows_policy.go
  internal/pkg/utils/winpol/windows_policy_test.go
  pkg/dataplane/dataplane.go
  pkg/dataplane/dataplane_linux.go
  pkg/dataplane/dataplane_windows.go
  pkg/dataplane/grpc/grpc_dataplane.go
  pkg/dataplane/grpc/test_server_linux.go
  pkg/dataplane/linux/dataplane_linux.go
  pkg/dataplane/windows/dataplane_windows.go
  pkg/install/install.go
  pkg/ipamplugin/ipam_plugin.go
  pkg/k8s/k8s.go
  pkg/plugin/plugin.go
  pkg/types/types.go
  pkg/upgrade/migrate.go
  tests/calico_cni_ipam_test.go
  tests/calico_cni_test.go
  win_tests/calico_cni_k8s_windows_test.go
  win_tests/calico_cni_windows_suite_test.go
Labels: docs-pr-required, release-note-required

#925 Remove flag windows_disable_host_subnet_nat_exclusion
  internal/pkg/utils/network_linux.go
  internal/pkg/utils/network_windows.go
  internal/pkg/utils/winpol/windows_policy.go
  pkg/dataplane/windows/dataplane_windows.go
  pkg/k8s/k8s.go
  pkg/types/types.go
Labels: docs-pr-required, release-note-required

#904 Add validate cni.conf to be valid json
  Dockerfile.amd64
  pkg/install/install.go
  pkg/install/install_test.go
Labels: docs-pr-required, release-note-required

#927 File logging
  go.mod
  go.sum
  internal/pkg/utils/utils.go
  pkg/install/install.go
  pkg/install/install_test.go
  pkg/ipamplugin/ipam_plugin.go
  pkg/k8s/k8s.go
  pkg/plugin/plugin.go
  pkg/types/types.go
  tests/calico_cni_k8s_test.go
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-completed, release-note-required

#929 Fill in resource version and UID when doing a delete.
  go.mod
  go.sum
  pkg/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#931 Use bin/windows as windows binary directory
  .semaphore/run-win-fv.sh
  .semaphore/semaphore.yml
  Makefile
Labels: docs-pr-required, release-note-required

#932 Merge pull request #931 from song-jiang/song-fix-bin
  .semaphore/run-win-fv.sh
  .semaphore/semaphore.yml
  Makefile
Labels: docs-pr-required, release-note-required

#933 [v3.16] Backport bpf fixes
  go.mod
  go.sum
  pkg/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#930 Fix that CNI plugin itself was only being included if make ut was run
  Makefile
Labels: docs-not-required, release-note-not-required

#936 Cherry-pick Merge pull request #913 from caseydavenport/casey-panic-recovery
  pkg/plugin/plugin.go
Labels: docs-not-required, release-note-not-required

#937 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#938 Fix release build
  Makefile
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#939 Fix that CNI plugin itself was only being included if make ut was run
  Makefile
Labels: docs-not-required, release-note-not-required

#942 Revert accidental change from KUBERNETES_NODE_NAME to NODENAME
  pkg/install/install.go
  pkg/install/install_test.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required
