Repository projectcalico/cni-plugin, pull requests merged in 2020-07, with the labels that each got.

#915 CVEs
  .dockerignore
  Dockerfile.amd64
  k8s-install/scripts/clean.sh
Labels: docs-pr-required, release-note-required

#913 Handle panics in the CNI plugin gracefully
  pkg/plugin/plugin.go
Labels: docs-not-required, release-note-required

#917 CVEs
  .dockerignore
  Dockerfile.amd64
  k8s-install/scripts/clean.sh
Labels: docs-pr-required, release-note-required

#916 CVEs
  .dockerignore
  Dockerfile.amd64
  k8s-install/scripts/clean.sh
Labels: docs-pr-required, release-note-required

#918 Reintroduce CMD in Dockerfile
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: docs-not-required, release-note-not-required

#919 Use relative path
  pkg/install/install.go
Labels: docs-not-required, release-note-not-required

#921 Upgrade to Golang 1.14
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-required

#923 Update gobuild v0.45
  Makefile
Labels: docs-not-required, release-note-not-required
