Repository projectcalico/cni-plugin, pull requests merged in 2020-03, with the labels that each got.

#849 Use mv to put binaries on host
  k8s-install/scripts/install-cni.sh
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#855 Automated cherry pick of #849: Use mv to put binaries on host
  k8s-install/scripts/install-cni.sh
Labels: docs-not-required, release-note-required

#854 Automated cherry pick of #849: Use mv to put binaries on host
  k8s-install/scripts/install-cni.sh
Labels: docs-not-required, release-note-required

#853 Automated cherry pick of #849: Use mv to put binaries on host
  k8s-install/scripts/install-cni.sh
Labels: docs-not-required, release-note-required

#852 Automated cherry pick of #849: Use mv to put binaries on host
  k8s-install/scripts/install-cni.sh
Labels: docs-not-required, release-note-required

#851 Automated cherry pick of #849: Use mv to put binaries on host
  k8s-install/scripts/install-cni.sh
Labels: docs-not-required, release-note-required

#850 Automated cherry pick of #849: Use mv to put binaries on host
  k8s-install/scripts/install-cni.sh
Labels: docs-not-required, release-note-required

#848 Add `hostname` to the image and pin image
  Dockerfile.amd64
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#846 Change ppc64le base image from debian slim to UBI
  Dockerfile.ppc64le
Labels: docs-not-required, release-note-required

#842 fix shell stderr redirect error
  k8s-install/scripts/install-cni.sh
Labels: docs-not-required, release-note-required

#858 Automated cherry pick of #848: Add `hostname` to the image and pin image
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#857 Automated cherry pick of #848: Add `hostname` to the image and pin image
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#856 Automated cherry pick of #848: Add `hostname` to the image and pin image
  Dockerfile.amd64
Labels: docs-not-required, release-note-required

#860 Add licenses to built image
  .dockerignore
  Dockerfile.amd64
  Dockerfile.arm64
  Dockerfile.ppc64le
  Dockerfile.s390x
  licenses/Apache-2.0
  licenses/BSD
  licenses/GPLv2
  licenses/ISC
  licenses/MIT
  licenses/Mozilla-public
Labels: docs-not-required, release-note-not-required

#862 Include more license information
  README.md
  licenses/Apache-2.0
  licenses/BSD
  licenses/ISC
  licenses/MIT
  licenses/Mozilla-public
Labels: docs-not-required, release-note-not-required
