Repository projectcalico/cni-plugin, pull requests merged in 2020-10, with the labels that each got.

#958 Update go-build version to v0.48 (go 1.15.2)
  Makefile
Labels: docs-not-required, release-note-not-required

#960 Create l2bridge without DNS info
  internal/pkg/testutils/utils_windows.go
  pkg/dataplane/windows/dataplane_windows.go
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-pr-required, release-note-required

#962 Respect /var/lib/calico/mtu file
  internal/pkg/utils/utils.go
  pkg/plugin/plugin.go
  tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-required

#963 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
