Repository projectcalico/cni-plugin, pull requests merged in 2021-06, with the labels that each got.

#1086 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#1087 Replace lib/v3 package with projectcalico/api
  go.mod
  go.sum
  internal/pkg/testutils/utils.go
  pkg/k8s/k8s.go
  pkg/plugin/plugin.go
  pkg/upgrade/migrate.go
  tests/calico_cni_k8s_test.go
  tests/calico_cni_test.go
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-pr-required, release-note-required

#1088 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1096 Update api pins on pin update
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1097 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1074 Simplify cni installation
  pkg/install/install.go
Labels: docs-not-required, merge-when-ready, release-note-not-required
