Repository projectcalico/cni-plugin, pull requests merged in 2021-05, with the labels that each got.

#1077 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1076 Set serviceaccount on new WEPs
  go.mod
  go.sum
  pkg/k8s/k8s.go
  tests/calico_cni_k8s_test.go
Labels: docs-pr-required, release-note-required

#1078 Automated cherry pick of #1076: Set serviceaccount on new WEPs
  go.mod
  go.sum
  pkg/k8s/k8s.go
  tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-not-required

#1079 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1031 Add armv7 build
  Dockerfile.armv7
  Makefile
Labels: docs-not-required, release-note-not-required

#1080 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1082 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1083 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1084 Refactor makefile for new cd / release flow
  Makefile
Labels: docs-not-required, release-note-not-required

#1085 Retry calico client retrieval on failure in windows test
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-not-required, release-note-not-required
