Repository projectcalico/cni-plugin, pull requests merged in 2021-08, with the labels that each got.

#1116 create multi queue veth for xdp
  go.mod
  go.sum
  pkg/dataplane/linux/dataplane_linux.go
  pkg/plugin/plugin.go
  pkg/types/types.go
  tests/calico_cni_k8s_test.go
  tests/calico_cni_test.go
Labels: docs-pr-required, release-note-required

#1135 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1137 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1138 Change release repo to docker.io, add RELEASE and CONFIRM env variables
  Makefile
Labels: docs-not-required, release-note-not-required

#1139 Automated cherry pick of #1138: Change release repo to docker.io, add RELEASE and CONFIRM env
  Makefile
Labels: docs-not-required, release-note-not-required

#1140 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1142 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1143 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1144 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1141 Update CNI plugin version to v1.0.0
  Makefile
Labels: release-note-required, docs-not-required

#1145 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1147 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1151 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
  pkg/k8s/k8s.go
  tests/calico_cni_k8s_test.go
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-not-required, release-note-not-required
