Repository projectcalico/cni-plugin, pull requests merged in 2021-02, with the labels that each got.

#1010 Ensure that in dual stack environments, addresses are not leaked when either IPv6 or IPv4 addresses are not available
  pkg/ipamplugin/ipam_plugin.go
  tests/calico_cni_ipam_test.go
Labels: docs-not-required, release-note-required

#1011 Remove host route on endpoint with vxlan
  .semaphore/run-win-fv.sh
  .semaphore/semaphore.yml
  pkg/dataplane/windows/dataplane_windows.go
Labels: docs-pr-required, release-note-required

#1012 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1013 Fix datastore lock getting stuck during ipam migration
  pkg/upgrade/migrate.go
Labels: docs-not-required, merge-when-ready, release-note-required

#1015 Fix ipam migration datastore lock 3.17
  pkg/upgrade/migrate.go
Labels: docs-not-required, merge-when-ready, release-note-required

#1016 Remove route encap policy for endpoint
  internal/pkg/utils/winpol/windows_policy.go
  internal/pkg/utils/winpol/windows_policy_test.go
  pkg/dataplane/windows/dataplane_windows.go
Labels: docs-pr-required, release-note-required

#1017 Added encap route policy for l2bridge
  pkg/dataplane/windows/dataplane_windows.go
Labels: docs-pr-required, release-note-required

#1018 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1020 Fix network id comparision for Windows OS 2004
  pkg/dataplane/windows/dataplane_windows.go
Labels: docs-not-required, release-note-required

#1021 Fix network id comparision on Windows OS 2004
  pkg/dataplane/windows/dataplane_windows.go
Labels: docs-pr-required, release-note-required

#1024 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1026 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
