Repository projectcalico/cni-plugin, pull requests merged in 2021-10, with the labels that each got.

#1172 Fix windows FV issues
  .semaphore/cleanup.yml
  .semaphore/run-win-fv.sh
Labels: docs-not-required, release-note-not-required

#1173 Automated cherry pick of #1172: Fix winfv cleanup script
  .semaphore/cleanup.yml
  .semaphore/run-win-fv.sh
Labels: docs-not-required, release-note-not-required

#1174 Automated cherry pick of #1172: Fix winfv cleanup script
  .semaphore/cleanup.yml
  .semaphore/run-win-fv.sh
Labels: docs-not-required, release-note-not-required

#1175 Automated cherry pick of #1172: Fix winfv cleanup script
  .semaphore/cleanup.yml
  .semaphore/run-win-fv.sh
Labels: docs-not-required, release-note-not-required

#1181 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1171 [allowed-use] Supply intended use on IPAM API.
  go.mod
  go.sum
  pkg/ipamplugin/ipam_plugin.go
  tests/calico_cni_k8s_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#1185 Use go build command from Makefile.commmon
  Makefile
Labels: release-note-required, docs-pr-required

#1186 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1194 Fix boringssl check for other archs
  Makefile
Labels: docs-pr-required, release-note-not-required, merge-when-ready

#1119 Add HostPort support in the gRPC dataplane
  pkg/dataplane/grpc/grpc_dataplane.go
  pkg/dataplane/grpc/proto/cnibackend.pb.go
  pkg/dataplane/grpc/proto/cnibackend.proto
Labels: release-note-required, docs-not-required, merge-when-ready
