Repository projectcalico/cni-plugin, pull requests merged in 2021-09, with the labels that each got.

#1154 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1155 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1156 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1160 report conflicting device when we fail to add route
  pkg/dataplane/linux/dataplane_linux.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#1161 report conflicting device when we fail to add route
  pkg/dataplane/linux/dataplane_linux.go
Labels: release-note-required, docs-not-required, merge-when-ready

#1162 report conflicting device when we fail to add route
  pkg/dataplane/linux/dataplane_linux.go
Labels: release-note-required, docs-not-required, merge-when-ready

#1159 [master] Semaphore Auto Pin Update
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1164 report conflicting device when we fail to add route
  pkg/dataplane/linux/dataplane_linux.go
Labels: release-note-required, docs-not-required

#1167 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#1170 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
