Repository projectcalico/cni-plugin, pull requests merged in 2021-01, with the labels that each got.

#1007 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1002 Remove uses of Fatal on the main CNI plugin path.
  pkg/k8s/k8s.go
Labels: docs-not-required, release-note-not-required

#1003 Add more logs to ease debugging calico upgrade
  pkg/upgrade/migrate.go
Labels: docs-not-required, release-note-not-required

#1008 Fix that we were returning an error when we shouldn't
  pkg/plugin/plugin.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#1009 Add timestamp to IPAM allocations
  go.mod
  go.sum
  pkg/ipamplugin/ipam_plugin.go
Labels: docs-not-required, release-note-not-required
