Repository projectcalico/cni-plugin, pull requests merged in 2021-03, with the labels that each got.

#1029 Fix winfvs not running
  .semaphore/run-win-fv.sh
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#1030 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1032 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1033 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1035 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1036 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1037 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1038 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1040 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1041 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1043 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1042 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1044 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1045 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1046 Fix WinFV (#1029)
  .semaphore/run-win-fv.sh
  .semaphore/semaphore.yml
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1048 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1050 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1052 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
