Repository projectcalico/cni-plugin, pull requests merged in 2021-07, with the labels that each got.

#1099 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1092 windows: Remove assertion that fails when container creation is slow
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-not-required, release-note-not-required

#1103 Update call to AutoAssign() to use IPAMAssignments struct
  go.mod
  go.sum
  pkg/ipamplugin/ipam_plugin.go
  tests/calico_cni_k8s_test.go
Labels: docs-not-required, release-note-not-required

#1105 Pin update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1104 windows: update EnsureVXLANTunnelAddr so we can call it from node
  internal/pkg/utils/network_linux.go
  internal/pkg/utils/network_windows.go
  pkg/dataplane/windows/dataplane_windows.go
  pkg/k8s/k8s.go
Labels: docs-not-required, release-note-required

#1093 Automated cherry pick of #1092: windows: Remove assertion that fails when container creation
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-not-required, release-note-not-required

#1094 Automated cherry pick of #1092: windows: Remove assertion that fails when container creation
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-not-required, release-note-not-required

#1095 Automated cherry pick of #1092: windows: Remove assertion that fails when container creation
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-not-required, release-note-not-required

#1107 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1108 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1109 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1113 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1112 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1115 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1114 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1118 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1106 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1121 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1123 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1071 Fix apache-2 license text
  internal/pkg/testutils/utils_windows.go
  internal/pkg/utils/network_linux.go
  internal/pkg/utils/network_windows.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1117 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1126 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1127 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1122 Fix up tests after adding KDD container ID support.
  tests/calico_cni_k8s_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1125 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1128 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1129 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1130 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1131 Update release targets
  Makefile
Labels: docs-not-required, release-note-not-required

#1132 Update release targets
  Makefile
Labels: docs-not-required, release-note-not-required

#1134 Automated cherry pick of #1133: Fix release target
  Makefile
Labels: docs-pr-required, release-note-required

#1133 Fix release target
  Makefile
Labels: docs-pr-required, release-note-required
