Repository projectcalico/cni-plugin, pull requests merged in 2021-04, with the labels that each got.

#1053 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1058 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1059 Clean up Makefile
  Makefile
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1047 Build images before publishing and don't do auto pin updates
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#1056 Extend semaphore job timeout to 2 hours
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#1064 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#1054 windows - use HNS V2 APIs for CRI-compliant runtimes
  .semaphore/run-win-fv.sh
  .semaphore/semaphore.yml
  go.mod
  go.sum
  internal/pkg/testutils/utils_windows.go
  internal/pkg/utils/cri/cri.go
  internal/pkg/utils/hcn/hcn_linux.go
  internal/pkg/utils/hcn/hcn_windows.go
  internal/pkg/utils/network_linux.go
  internal/pkg/utils/network_windows.go
  internal/pkg/utils/winpol/windows_policy.go
  internal/pkg/utils/winpol/windows_policy_test.go
  pkg/dataplane/windows/dataplane_windows.go
  pkg/k8s/k8s.go
  win_tests/calico_cni_k8s_windows_test.go
Labels: docs-pr-required, release-note-required

#1065 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1066 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1067 windows: Fix OutBoundNAT policies not being added to endpoint
  internal/pkg/utils/winpol/windows_policy.go
  internal/pkg/utils/winpol/windows_policy_test.go
Labels: docs-not-required, release-note-not-required

#1068 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1069 [v3.19] windows: Fix OutBoundNAT policies not being added to endpoint (#1067)
  internal/pkg/utils/winpol/windows_policy.go
  internal/pkg/utils/winpol/windows_policy_test.go
Labels: docs-not-required, release-note-not-required

#1070 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1072 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required
